version: "2"
services: 

    keystone:
        build: .
        volumes:
            - / /home/app
        ports:
          - 3000:3000

    db:
      image: mongo
      environment:
        MONGO_INITDB_DATABASE: keystone
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: toor

    # mongo-express:
    #   image: mongo-express
    
    #   ports:
    #     - 8081:8081
    #   environment:
    #     # ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #     # ME_CONFIG_MONGODB_ADMINPASSWORD: toor
    #     # MONGO_INITDB_ROOT_USERNAME: root
    #     # MONGO_INITDB_ROOT_PASSWORD: toor
    #     ME_CONFIG_MONGODB_SERVER: db
    #     ME_CONFIG_BASICAUTH_USERNAME: root
    #     ME_CONFIG_BASICAUTH_PASSWORD: toor
